---
title: "graphql-requestのエラーの型が分からない"
emoji: "🤔"
type: "tech"
topics: ["typescript", "graphql"]
published: true
---

Next.js v13でGraphQLをpromiseで使うために`graphql-request`を使っているのですが、エラーの型が分からなかったのでメモ。
`typed-document-node`で記述しています。

```tsx:graphql-request
const Component = () => {
  
  const handleMutate = async () => {
    try {
      await new GraphQLClient('').request(HogeDocument).catch((e) => {
        e // any
      })
    } catch (e) {
      e // unknown
    }
  }
}
```

## URQL
`CombinedError`を使って判定が可能。   
返り値に`error`が含まれるので`catch`でキャッチする必要はない。
https://formidable.com/open-source/urql/docs/api/core/#combinederror

```tsx:URQL
const Component = () => {
  const [,muattion] = useMutation(HogeDocument)

  const handleMutate = async () => {
    try {
      const { error } = await mutate()
      if (error) {
        error.graphQLErrors // GraphQLError[] 
      }
    } catch (e) {
      console.log(e) // その他のエラー
    }
  }
}
```

## Apollo Client

`ApolloError`を使って判定が可能。
返り値に`error`を含むし`catch`でも取得できる。
https://github.com/apollographql/apollo-client/blob/main/src/errors/index.ts#L44

```tsx:Apollo Client
const Component = () => {
  const [mutate] = useMutation(HogeDocument)
  
  const handleMutate = async () => {
    try {
      const { error } = await mutate()
      if(errors) {
        errors  // ReadonlyArray<GraphQLError>
      }
    } catch (e) {
      if (e instanceof ApolloError) {
        e.graphQLErrors // ReadonlyArray<GraphQLError>
      }
    }
  }
}
```

## graphql-request

GraphQLのエラーは`200`で返ってくるのに`catch`できるので何かしらエラーの加工をしているっぽい。

https://github.com/prisma-labs/graphql-request#error-handling
https://github.com/prisma-labs/graphql-request/blob/master/examples/error-handling.ts#L23-L26
しかし、公式の`Error handling`の項目を見ても`console.error(JSON.stringify(error, undefined, 2))`としか書いておらず、型が分からない。

`src/types.ts`を見てみると、`GraphQLResponse`の`error`の型が`GraphQLError`となっている。
https://github.com/prisma-labs/graphql-request/blob/c17f82138e5c0e7960fd1fb2ba9ef439323d57dc/src/types.ts#L14-L20

この`GraphQLResponse`が使われている箇所を探すと`ClientError`にたどり着いたので、`ClientError`の`instanceof`で判定するとほしい型が手に入りそうだった。
https://github.com/prisma-labs/graphql-request/blob/master/src/types.ts#L27-L28

```tsx
const Component = () => {
  
  const handleMutate = async () => {
    try {
      await new GraphQLClient('').request(HogeDocument).catch((e) => {
        if (e instanceof ClientError) {
          e.response.errors // GraphQLError[] | undefined
        }
      })
    } catch (e) {
      if (e instanceof ClientError) {
        e.response.errors // GraphQLError[] | undefined
      }
    }
  }
}
```

`error`を`ClientError`の`instanceof`で判定した後、`e.response.errors`にアクセスすると`GraphQLError[]`or`undefined`が取得できる。